language: ruby
sudo: true
dist: trusty

install: gem install html-proofer

script: htmlproofer --check-html --checks-to-ignore ImageCheck

branches:
  only:
    - master

notifications:
    email: false
