language: ruby
sudo: true
dist: trusty

install: gem install html-proofer

script: htmlproofer --check-html --check-favicon --url-ignore cdn.mhsengineering.club

branches:
  only:
    - master

notifications:
    email: false
