language: ruby
sudo: true
dist: trusty

install: gem install html-proofer

script: htmlproofer --check-html --disable-external --enforce-https --check-favicon

branches:
  only:
    - master

notifications:
    email: false
